import { openai } from "../config/openai.js";
import * as searchOrchestrator from '../services/combinedAliment.service.js'; 


export async function generateDietSuggestion(userData) {
    const { name, weight, height, objective, activity_lvl } = userData;

    let availableFoodsString = "No specific food catalog provided."; 

    try {
        const { products } = await searchOrchestrator.searchCombined({ query: null }); 
        const foodNamesArray = products.map(p => p.name || `${p.brand} product`);
        
        if (foodNamesArray.length > 0) {
            availableFoodsString = foodNamesArray.join(', ');
        }
        
        if (foodNamesArray.length === 0) {
             console.warn("Catalog search returned an empty list. AI will use generic foods.");
        }
        
    } catch (e) {
        console.error("Failed to retrieve available food list from combined service:", e.message);
    }

    const systemContent = `
      You are a professional nutritionist and a highly structured JSON generator. Your task is to output a perfect JSON object following the provided structure and rules.

      **STRICT OUTPUT PROTOCOL:**
      1.  **Structure:** The output MUST contain four keys ('breakfast', 'lunch', 'dinner', 'snacks'). Each of these keys MUST contain an **OBJECT**.
      2.  **Item Keys:** The nested object (e.g., 'breakfast') MUST use sequential keys starting from 'item1' (e.g., 'item1', 'item2', 'item3', etc.).
      3.  **Item Value (CRITICAL CHANGE):** The value of each 'itemN' key MUST be an object with exactly three keys: **"name"** (string), **"quantity"** (number), and **"measurement_unit"** (string).
      4.  **Unit Format (CRITICAL):** The "measurement_unit" value MUST be ONLY one of the following: **g, kg, ml, L, or un** (for unit/slice/piece). The "quantity" MUST be a numerical value.
          * **Example of Conversion:** "2 slices" MUST be converted to {"quantity": 2, "measurement_unit": "unid"}.
      5.  **Food Source:** You MUST only use ingredients and meals listed in the 'AVAILABLE FOODS' section.
      6.  **Total Calories:** You MUST NOT include the "totalCalories" key.

      The required JSON format is:
      {
        "breakfast": {
          "item1": { "name": "Food 1 Name", "quantity": 100, "measurement_unit": "g" },
          "item2": { "name": "Food 2 Name", "quantity": 200, "measurement_unit": "ml" }
        },
        "lunch": { ... },
        "dinner": { ... },
        "snacks": { ... }
      }
    `;

    const prompt = `
      You are a professional nutritionist.
      Generate a personalized diet suggestion for:
      - Name: ${name}
      - Weight: ${weight} kg
      - Height: ${height} cm
      - Goal: ${objective}
      - Activity level: ${activity_lvl}

      AVAILABLE FOODS:
      [${availableFoodsString}] 

      **IMMEDIATE ACTION REQUIRED:** You MUST strictly adhere to the **STRICT OUTPUT PROTOCOL** defined in the system message, ensuring the **quantity** is a number and **measurement_unit** is a string, and avoiding the "totalCalories" key.

      Output a structured JSON with:
      {
        "breakfast": { "item1": { ... }, ... },
        "lunch": { ... },
        "dinner": { ... },
        "snacks": { ... },
      }
      Return to me just the JSON, without any other info or it will break my code. Use the specified **JSON** format.
    `;

  try {
    const completion = await openai.chat.completions.create({
      messages: [
        { role: "system", content: systemContent },
        { role: "user", content: prompt },
      ],
      temperature: 0.2,
      max_tokens: 1000,
      response_format: { type: "json_object" },
    });
    const content = completion.choices[0].message.content;
    try {
            const dietObject = JSON.parse(content);
            return dietObject;
        } catch (e) {
            console.error("ERROR: Failed to parse the JSON generated by the AI. Raw content:", content);
            throw new Error(`The AI returned an invalid format: ${content.substring(0, 100)}...`);
        }
  } catch (error) {
      console.error("Error in OpenAI API call:", error);
      throw error;
  }
}